### ISSUE TITLE
Centos:7 same basic version but different image (different timestamps)

### ISSUE THREAD

**Issue by msperl** [CentOS/sig-cloud-instance-images#122]
Why is the image centos:centos7 not identical (i.e not a tag) to centos:centos7.5.1804?

The build time is (almost) identical:
```
[...]$  docker inspect centos:centos7  --format "{{ .Created }}"
2018-08-06T19:21:48.235227329Z
[...]$  docker inspect centos:centos7.5.1804  --format "{{ .Created }}"
2018-08-06T19:23:48.587844012Z
```

It would be nice if these were the same as they are based on the same image just a different tag...

Martin

P.s: as a side-note the labels are not correct in centos:centos7.5.1804:
```
[...]$  docker inspect centos:centos7.5.1804 | jq .[].Config.Labels
{
  "org.label-schema.schema-version": "= 1.0     org.label-schema.name=CentOS Base Image     org.label-schema.vendor=CentOS     org.label-schema.license=GPLv2     org.label-schema.build-date=20180531"
}
```
Whereas centos:centos7 shows:
```
[...]$  docker inspect centos:centos7 | jq .[].Config.Labels
{
  "org.label-schema.build-date": "20180804",
  "org.label-schema.license": "GPLv2",
  "org.label-schema.name": "CentOS Base Image",
  "org.label-schema.schema-version": "1.0",
  "org.label-schema.vendor": "CentOS"
}
```
(which I assume is "correct")

**Comment by jperrin** [comment]
There are a couple things going on here:

1. The full minor version 7.5.1804 is built to match the install media. They do not get updates, and are not modified.

The short versioned images centos:centos7 is a rolling release on a monthly schedule that includes updated packages. 

2. For some reason you don't appear to have the latest image, which should have been updated roughly a month ago in commit https://github.com/CentOS/sig-cloud-instance-images/commit/24c0d04946b72e37776309224712b5f05aa52639

There should be new images coming out in the next week or so. 

3. You are correct, the tags are broken in the 7.5.1804 image, but since these images don't get updates, they will stay broken until the next minor release of 7.6.<releasedate>
