### ISSUE TITLE
CentOS 6.5 Docker image?

### ISSUE THREAD

**Issue by apennebaker-ni** [CentOS/sig-cloud-instance-images#13]
Docker Hub provides several authoritative versions of CentOS, but not CentOS 6.5:

https://registry.hub.docker.com/_/centos/tags/manage/

Could we please add a tag/image for this?

**Comment by jperrin** [comment]
We made the decision to tag minor versions with 6.6 on. I don't see a reason to resurrect an outdated image that we won't support. Especially given that most of the packages in what would be a 6.5 container have recently have CVE's with names. (glibc, openssl, bash, etc)

**Comment by yoanisgil** [comment]
I understand that CentOS 6.5 is no longer supported but there are still quite a few people/companies using it and for whom moving to a more recent choice is not an immediate choice. At the very least you still provide the image and warn users that is strongly recommended to use a more recent version.

**Comment by andrzejwp** [comment]
+1 @yoanisgil 
please resurrect 6.5.

**Comment by robertoaloi** [comment]
I second the request. A CentOS 6.5 would help.

**Comment by robertoaloi** [comment]
Is it possible to reference a SHA somehow, rather than a tag? Maybe that could be an option for those who need to refer to a CentOS 6.5, while keeping that unsupported. Talking as a complete Docker ignorant here, so feel free to scream.

**Comment by jperrin** [comment]
The issue here is if we provide 6.5, then why not 6.4, 6.3, etc on down the list. They are unsupported. They have security holes, and we would be exposing users (who clearly aren't interested in keeping current, or secure) to all sorts of fun things (shell shock, heartbleed, glibc vulnerabilities, etc), simply for their convenience because they are unwilling to update. 

For a rather blunt comparison... do you buy an alcoholic a beer, or help them quit? At what point do we become an enabler?

**Comment by gtirloni** [comment]
Red Hat's support for RHEL 6.5 is only provided if you buy their [Extended Update Support](https://access.redhat.com/support/policy/updates/errata) and even that will end in November 2015. Please read [this](https://access.redhat.com/articles/64664) article for information on how they deal with non-current minor releases (they ask you to update).

If you want to deploy CentOS 6.5 today you're setting yourself up for failure (or you've an EUS contract and thus not using CentOS). I'd be curious to read more about particular scenarios that require CentOS 6.5 and how the latest minor release can't be used.

**Comment by yoanisgil** [comment]
The only scenario I can possible think of is that where you, as an
individual, have to miserably stick to an unsupported version of CentOS
because your entire eco system is build on top of it.

However i do understand, and fully supported it, the rationale behind no
longer providing support for CentOS 6.5.

Bests,

Yoanis

**Comment by channprj** [comment]
There's resonable feedback from jperrin, so I think this issue would be close. It's confusing.
