### ISSUE TITLE
centos 7.6 build missing

### ISSUE THREAD

**Issue by dsmorse** [CentOS/sig-cloud-instance-images#133]
I know 7.6 just got promote as the latest release.  Is someone working on cutting a release for dockerhub?  Do you want me to submit a PR?

**Comment by ghost** [comment]
Some other users requested already an image with the new CentOS release #130

No need for a PR the build script should work with the new release, doesn't it?
https://github.com/CentOS/sig-cloud-instance-build/tree/master/docker

**Comment by dsmorse** [comment]
nice...   glad I asked.  
Yup I the referenced repo locally and that is how I am producing the tar.xz

**Comment by mnaser** [comment]
Hi @jperrin !

Sorry for the bother, but I'm coming in from OpenStack Ansible upstream world and our jobs have been broken with the release of 7.6 because we use this container and the mismatch between our host (7.6) and the container (7.5) is breaking things.

If there's anything that we can do to help add this, I'd be more than happy, if you want me to submit a PR, I'd be more than happy to as well (but I figure for `$security` reasons, you probably want to push it yourself).

I know I might be sounding a little impatient but it has indeed broken all of our CI, unfortunately: http://zuul.openstack.org/builds?job_name=openstack-ansible-deploy-aio_lxc-centos-7

Thank you!
Mohammed (OpenStack Ansible PTL)

**Comment by jperrin** [comment]
The containers should be published shortly.

**Comment by jperrin** [comment]
Closing, as 7.6.1810 (finally) showed up on the docker hub.
