### ISSUE TITLE
centos:7 updates

### ISSUE THREAD

**Issue by dtshepherd** [CentOS/sig-cloud-instance-images#163]
The `centos:7` has not been updated within the last 4 months.  Is that expected?  We used to see this image updated with the monthly builds.  Without these updates, security scanning tools find CVE vulnerabilities that are not patched.

The current work-around is to run `yum update` in our Dockerfile to make sure everything is updated, but that adds an unnecessary layer to the image.

**Comment by nunofernandes** [comment]
With the recent release of centos 7.8, the docker wasn't updated and is still based on centos 7.7. It would be awesome that the centos:7 image on docker hub would be updated to the latest released version of centos 7.

**Comment by nunofernandes** [comment]
Continuing on this note, `registry.centos.org/centos/centos:7` is even worse:

```
$ docker run -ti --rm registry.centos.org/centos/centos:7
Unable to find image 'registry.centos.org/centos/centos:7' locally
7: Pulling from centos/centos
e6a50b627bcb: Pull complete 
Digest: sha256:b8b72fb577559d8ee76171c93e7228a2a3e6dd1c73eeb8161190930acbbe59a3
Status: Downloaded newer image for registry.centos.org/centos/centos:7
[root@6fe6b1862f88 /]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
```

**Comment by qhaas** [comment]
Releases of nvidia cuda docker images are being delayed due to [detected vulnerabilities](https://gitlab.com/nvidia/container-images/cuda/-/issues/76#note_380174191) in the base centos images on docker hub.  They have likely already been fixed upstream.  Updated images would be appreciated.

Update:  According to [this post](https://gitlab.com/nvidia/container-images/cuda/-/issues/70#note_384001558), some organizations can't do a `yum update` to address the CVEs and can't release their derived images until there are no major CVEs.

**Comment by qhaas** [comment]
@bstinsonmhk , any luck getting these CentOS 7 images updated?

Would be great if container image updates coincided with the monthly 'Patch Tuesday' CentOS equivalent so we can get those major CVEs patched for big organizations, like nVidia, that can't release their downstream images without said patches.

**Comment by bstinsonmhk** [comment]
These should have gone out today
