### ISSUE TITLE
Centos7 image kernel version

### ISSUE THREAD

**Issue by sudhevan** [CentOS/sig-cloud-instance-images#31]
Hi
Need some clarification regarding the kernel version of the operating system in centos docker latest image (centos7). 
Uname -r gives version as 2.xxx ( I am running centos image on Enterprise RHEL 6.x)

Isn't 2.x very old kernel? I believe latest kernel is 7.x?
As per red hat running docker itself is not recommended on RHEL6 Because RHEL6 is running on kernel 2.x?
 Why is centos image running 2.x kernel?

Thanks

**Comment by jperrin** [comment]
docker containers aren't a VM. They share the host's kernel. Since you're running EL6 on the host, all the docker containers will see the 2.6 kernel. 

Yes, 2.6 is very old. It is what was current when EL6 was released. EL6 is version-locked. Fixes and security updates are backported, but the same kernel/gcc etc will exist for the life of the distribution (10 years). 

There are planned features in docker's future that will be incompatible with the 2.6 kernel. RedHat has stated that they may not backport the necessary changes to the 2.6 kernel. This means that running docker on a RHEL6 host is done at your own risk. 

Ideally you would run an EL7 host or an EH7 atomic host for your docker containers.

**Comment by sudhevan** [comment]
Understand, thanks for the information. I am in the process of upgrading my server to RHEL7.
Is it ok to run Sentos image on RHEL6/7 ? Is there an official RHEL docker image? does it really matter since my container is going to use host kernal? 
Thanks.

**Comment by jperrin** [comment]
Yes, you can run CentOS 6 or 7 images on a RHEL host just fine. Yes there is an official RHEL docker base container. You should use the image that best suits your needs. Since they both work, it's up to you which you choose to go with.
