### ISSUE TITLE
Latest centos7 image seems to be missing some packages

### ISSUE THREAD

**Issue by sidharta-s** [CentOS/sig-cloud-instance-images#40]
I did a diff of the packages between an older centos7 image and the latest one from this week. I found that the following packages have been removed :

```
 ethtool
 file
 groff-base
 iproute
 iptables
 less
 libcroco
 libgomp
 libmnl
 libnetfilter_conntrack
 libnfnetlink
 libunistring
 lzo
 snappy
 systemd-container
 systemd-container-libs
 which
```

Its surprising that some common tools have been removed - which, file, less and networking toolsets like iproute.  What is the expectation with the 'standard' centos:centos7 image - is it possible that tools/libraries will change when the same tag is updated? Are images that use centos:centos7 as the base image expected to explicitly ensure that such tools are installed?

This image has been very useful to us and we are thankful to the centos community for making it available.

**Comment by jperrin** [comment]
This was done somewhat intentionally at the 7.2.1511 update. The majority of it was done by request (via bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1273938) in order to keep a consistent container base. I don't envision changing the container contents too much from this point on, apart from updates and metadata improvements.

systemd-container was deprecated and replaced by systemd. This was an upstream change to remove a problem area solved initially by fakesystemd, and systemd-container.

**Comment by jperrin** [comment]
Adding to this after some thought, if you can make a case for any of the packages I've removed, either here on in the linked redhat bugzilla, I will consider restoring them, and petitioning rh to do the same. Feedback is difficult to come by, so anything you'd care to offer would be welcomed.

**Comment by sidharta-s** [comment]
Here are the packages that we have found to be particularly useful : which, file, less, iproute. I believe these should continue being a part of the base image. It is fairly common, for example, to use 'ip' to look at the networking setup within a container (e.g when someone spins up a bare centos7 container and wants to poke around) . I understand the motivation to keep the image compact in size, but IMO, it makes the standard image a little less useful if some fairly standard tools are missing by default.

**Comment by sidharta-s** [comment]
By the way, we discovered the missing packages when rebuilding images that are based off of centos:centos7 . Some tools/scripts broke ( 'ip' was missing ).

**Comment by jperrin** [comment]
Thank you for the feedback. In order to 'sell' this to the upstream folks, I need something of a "this is broken without $foo". That the tools broke because the command was missing is incidental (from a distro packaging perspective, certainly not yours) to the package not being done right in the first place. 

Is there a compelling reason (debug, LSB requirement, something I'm missing)for these tools to be in the container, or is my breaking your build simply a one-off? 

With what you've provided so far, the answer I get back will likely be to point you at super-privileged containers to use for debugging.

**Comment by sidharta-s** [comment]
Well, in hindsight, I guess it would have been better for us to use a fixed/stable tag of the centos image (e.g centos/centos7.1.1503) instead of using centos/centos7 which can change. That said, it does make it harder for folks to upgrade to newer centos7 images if commonly used packages are removed between minor versions. I believe which/less/file/iproute are widely used for debugging, building tools or simply poking around with centos containers (granted that privileged containers or containers with additional capabilities are necessary in some of these scenarios). If these reasons alone are not sufficient to consider re-including these packages in the base image, we’ll work around it - most likely by going back to an older centos 7.1 tag.  

Thanks for your help.

**Comment by sidharta-s** [comment]
So it looks like going back to the 7.1 image might be a problem. Please see my comment on #38

**Comment by lamerman** [comment]
@jperrin maven uses which and now it's broken :) So it's one more tool that was broken to sell it to 'upstream folks'

**Comment by andyneff** [comment]
@jperrin, I agree with the removal. But as for the requested feedback....

rpmbuild is broken without which

I started a discussion here https://lists.centos.org/pipermail/centos-devel/2016-January/014193.html

That being said, I still think which should be added to the rpm-build spec instead of adding it back into the docker image... However it may be friendlier to add which back until these issues are resolved?

**Comment by alapidas** [comment]
FWIW, we got bit today by `iproute`  and `snappy` being removed.  Reducing churn in images is pretty important when building your own images and relying on things in the base (and using this as a base image)

**Comment by jperrin** [comment]
@alapidas agreed. There shouldn't be much more churn after this batch for a while. The entire idea the last time was to reduce differences with upstream. 

That said, I would really advise everyone building containers (regardless of the platform, rhel, debian, ubuntu, fedora, etc) to explicitly call out what they're using. Assumptions cause tears.

**Comment by alapidas** [comment]
Agreed RE calling out images - I see that there are more specific tags.  We will probably pin down to specific tags moving forward.  Thanks @jperrin !

**Comment by geerlingguy** [comment]
I hit the case of the missing `which` as well; other tools I could expect to have to install on a truly minimal image, but I know I rely on `which` heavily to quickly determine whether something's in the user's $PATH during container builds and testing... I vote for getting it back in at least.

**Comment by jperrin** [comment]
in place of 'which', I might suggest 'type' as it's a bash builtin and sure to be in just about every container no matter what.

**Comment by stavrosg** [comment]
Anyway to add them afterwards? Debian guy here, so rpm is a mystery to me.

**Comment by jperrin** [comment]
In your dockerfile, include `yum install -y package-you-want && yum clean all` as one of your steps.
