### ISSUE TITLE
hostname command not found

### ISSUE THREAD

**Issue by yohanakh** [CentOS/sig-cloud-instance-images#42]
hostname command does not exist in centos 7.1.1503 docker image.
It does exist in centos 7.0.1406 and 7.2.1511

Two questions:
- Does the hostname command exist in Centos 7.1 installation and not in the docker image?
- Is this intentionally ? Will it be fixed?

Thanks

**Comment by jperrin** [comment]
yes, the hostname command exists in 7.1 however during the docker build process the package it comes from was excluded for the 7.1.1503 container. 

These are point-in-time builds and are not updated, so while this was an oversight and not an intentional omission, it will not be fixed.

You can simply do a `yum -y install hostname` in your Dockerfile if you're using this particular image.

**Comment by yohanakh** [comment]
I understand that 7.1.1503 itself won't be fixed but will you release 7.1.x image with a fix ?

**Comment by jperrin** [comment]
No. 7.1.xx itself is no longer supported. we don't support minor point releases. So now that we're on 7.2.1511, that's where the focus is until the next release comes out. 

Try to think of it in terms of /7/ rather than with a point release. Any package you install now on a 7.1.xx container will (by default) come from a 7.2.xx repository.

**Comment by yohanakh** [comment]
Thanks!
