### ISSUE TITLE
/var/lock is a symlink to a non-existant directory

### ISSUE THREAD

**Issue by bexelbie** [CentOS/sig-cloud-instance-images#46]
/var/lock is a symlink to /run/lock which is not created in the base container image.

**Comment by pasikarkkainen** [comment]
Due to this issue it's impossible to install for example "iptraf-ng" rpm on centos:7 image from Dockerfile when building a custom centos7 image:

  Installing : iptraf-ng-1.1.4-4.el7.x86_64                               51/59
Error unpacking rpm package iptraf-ng-1.1.4-4.el7.x86_64

error: unpacking of archive failed on file /var/lock/iptraf-ng: cpio: mkdir
  Installing : unzip-6.0-15.el7.x86_64                                    52/59
error: iptraf-ng-1.1.4-4.el7.x86_64: install failed

**Comment by jperrin** [comment]
This appears to be fixed as of https://github.com/CentOS/sig-cloud-instance-build/commit/734e48629a5ebb34aa1324064a2a0da85dddb9ae

Updated container will be pushed in the next monthly build, roughly a week out.

Closing.
