### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by HarriL** [CentOS/sig-cloud-instance-images#47]
LABEL name="CentOS Base Image" \
    vendor="CentOS" \
    license="GPLv2" \
    build-date="2015-12-23"
should be changed.

Document https://docs.docker.com/engine/userguide/labels-custom-metadata/ proposes metadata standard: "To prevent naming conflicts, Docker recommends using namespaces to label keys using reverse domain notation."

Issue is that when you build something on top of the CentOS, then all LABELs are a mess. You can not find correct information and worst  is that, if someone is using e.g LABEL name=xxx it overrides CentOS version and you loose valid OS information. 

Here is  proposal:
LABEL org.centos.name="CentOS Base Image" \
    org.centos.vendor="CentOS" \
    org.centos.license="GPLv2" \
    org.centos.build-date="2015-12-23"

**Comment by jperrin** [comment]
This runs a bit counter to the guidance for labels here -> https://github.com/projectatomic/ContainerApplicationGenericLabels, which is what we're currently following.

**Comment by jperrin** [comment]
I've had a chance to sit down and review this a bit more, and am going to close this one as "wontfix" for now. 

The reason is that labels, like 'name' should always mean things. Once someone takes this base image and builds from it (say into a mariadb container) it stops being a base container, and becomes whatever they made. The named label should reflect that. With reverse domain namespacing, a user (or application) would have to hunt to find the proper name, and may find several. This seems suboptimal for every workload except tracking origin components.
