### ISSUE TITLE
Centos tarballs

### ISSUE THREAD

**Issue by imcsk8** [CentOS/sig-cloud-instance-images#52]
are the tarballs being generated automatically and uploaded to a repo or are you guys generating them on your own?

It could be nice to have them in a http server so the dockerfile download the tarball instead of being on the git repo. This would make the Dockerfile more portable

**Comment by jperrin** [comment]
The process we're using is the one established by Docker. I'm not a fan of storing tarballs in git, but it's their procedure. 
We can't have the Dockerfile pull the tarball because ADD statement of the dockerfile only unpacks the provided tarball if it's local. If we fetch the tarball as part of the Dockerfile, we add needless layers and can't properly unpack the tarball.
