### ISSUE TITLE
/var/run/nologin in centos:latest

### ISSUE THREAD

**Issue by crossbuilder** [CentOS/sig-cloud-instance-images#60]
The file "/var/run/nologin" wasn't there in previous images but is in the 20160701 build. Is this change intentional? Am I supposed to remove that file in my derived container to allow ssh login?

**Comment by jperrin** [comment]
This is due to a fix for https://github.com/CentOS/sig-cloud-instance-images/issues/46

The /run/ dir is tmpfs in a full distro install, but that won't work in containers. With this image /run (and all associated files) are properly created.

TL;DR, yes. you will need to remove this file from now on. sorry for the inconvenience.

**Comment by crossbuilder** [comment]
No inconvenience, just wanted to be sure, it is supposed to be this way. Thanks!

**Comment by juliantaylor** [comment]
is it really not possible to remove this file from the images?
it is somewhat confusing to have updated images suddenly disallow login with a "system is powering up" error message (especially when you are reading the centos6 manpage for pam_nologin while trying to fix it which does not list /var/run/nologin ._.)

**Comment by jperrin** [comment]
I wouldn't expect 6 to document it in this location, as it's a systemd thing.  I will remove this file in the next build of the container.
