### ISSUE TITLE
ppc64le/centos: No minor tags

### ISSUE THREAD

**Issue by rck** [CentOS/sig-cloud-instance-images#96]
The documentation at https://hub.docker.com/r/ppc64le/centos/ states that minor releases are tagged, which does not seem to be the case. If I try one of the examples (or minor tags that are available on 64bit x86), I get:
```
docker pull ppc64le/centos:6.6
Error response from daemon: manifest for ppc64le/centos:6.6 not found
```

`centos:latest` works as expected, so thank you guys for the great work. Having minor/release tags would be highly appreciated.

**Comment by jperrin** [comment]
There is no CentOS 6 build for ppc64le or arm64. The alternate architectures began support at 7.x, and since docker only recently began supporting multiarch properly, we didn't push images into the ppc64le or arm64 tempfix tags. 

Currently there are no minor tags for the altarch builds, but when the next minor release of 7 happens, we will add them.
